name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore SyncToyNext.slnx

      - name: Build
        run: dotnet build SyncToyNext.slnx --configuration Release --no-restore

      - name: Publish self-contained Linux x64
        run: dotnet publish SyncToyNext.Client/SyncToyNext.Client.csproj -c Release -r linux-x64 --self-contained true -o ./publish/linux-x64

      - name: Publish self-contained Windows x64
        run: dotnet publish SyncToyNext.Client/SyncToyNext.Client.csproj -c Release -r win-x64 --self-contained true -o ./publish/win-x64

      - name: Publish self-contained macOS x64
        run: dotnet publish SyncToyNext.Client/SyncToyNext.Client.csproj -c Release -r osx-x64 --self-contained true -o ./publish/osx-x64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SyncToyNext-Publish
          path: ./publish/
