name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: windows-latest
            rid: win-x64
          - os: macos-latest
            rid: osx-x64
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore SyncToyNext.slnx

      - name: Build
        run: dotnet build SyncToyNext.slnx --configuration Release --no-restore

      - name: Publish self-contained
        run: dotnet publish SyncToyNext.Client/SyncToyNext.Client.csproj -c Release -r ${{ matrix.rid }} --self-contained true -o ./publish/${{ matrix.rid }}

      - name: Delete old artifacts
        uses: c-hive/delete-artifact@v2
        with:
          name: SyncToyNext-Publish-${{ matrix.os }}-${{ matrix.rid }}
          failOnError: false

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SyncToyNext-Publish-${{ matrix.os }}-${{ matrix.rid }}
          path: ./publish/${{ matrix.rid }}
