name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rid: [linux-x64, win-x64, osx-x64]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore SyncToyNext.slnx

      - name: Build
        run: dotnet build SyncToyNext.slnx --configuration Release --no-restore

      - name: Publish self-contained
        run: dotnet publish SyncToyNext.Client/SyncToyNext.Client.csproj -c Release -r ${{ matrix.rid }} --self-contained true -o ./publish/${{ matrix.rid }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SyncToyNext-Publish-${{ matrix.rid }}
          path: ./publish/${{ matrix.rid }}
